# Generated by Django 3.1.1 on 2024-05-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='squaremeters',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
    ]
